import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {JSDOM,VirtualConsole} from 'jsdom';
import {setup,apply} from './helpers.mjs';
const html=readFileSync('student.html','utf8');
async function waitFor(predicate){for(let i=0;i<100;i++){if(predicate())return;await new Promise(r=>setTimeout(r,10));}throw Error('UI did not settle');}
function screen(f,{cookie='',staff=false,hash=''}={}){
 const errors=[];const console=new VirtualConsole();console.on('jsdomError',e=>errors.push(e));
 const dom=new JSDOM(html,{url:'https://classroom.test/student'+(staff?'#staff_session=teacher':hash),runScripts:'dangerously',virtualConsole:console,beforeParse(w){
  w.eval(readFileSync('vendor/qrcode.js.txt','utf8'));w.confirm=()=>true;w.URL.createObjectURL=()=> 'blob:test';w.URL.revokeObjectURL=()=>{};w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new w.Event('close'));};
  w.fetch=async(path,options={})=>{const r=await f.call(path,options.body?JSON.parse(options.body):undefined,{cookie,teacher:options.headers?.authorization==='Bearer teacher'});const set=r.headers.get('set-cookie');if(set)cookie=set.split(';')[0];return r;};
 }});return {dom,w:dom.window,errors};
}
test('teacher UI saves settings, creates an invite and approves a real application without losing button state',async()=>{const f=setup();await f.settings();const c=await f.auth();await apply(f,c);const {dom,w,errors}=screen(f,{staff:true});try{await waitFor(()=>w.document.querySelector('[data-review]'));assert.equal(w.document.querySelector('#staffView').classList.contains('hidden'),false);w.document.querySelector('#accessMode').value='auth';w.document.querySelector('#settingsForm').requestSubmit();await waitFor(()=>w.document.querySelector('#message').textContent==='บันทึกแล้ว');w.document.querySelector('#inviteForm').requestSubmit();await waitFor(()=>w.document.querySelector('#inviteOutput input'));assert.match(w.document.querySelector('#inviteOutput input').value,/student#invite=\d{16}$/);assert(w.document.querySelector('#inviteQr svg'));w.document.querySelector('[data-status="approved"]').click();await waitFor(()=>f.DB.db.prepare('SELECT status FROM student_applications').get().status==='approved');await waitFor(()=>w.document.querySelector('[data-member="revoke"]'));assert.equal(w.document.querySelector('[data-member="revoke"]').textContent,'ระงับสิทธิ์ห้องนี้');assert.deepEqual(errors,[]);}finally{dom.window.close();}});
test('student UI retains invite through login and direct entry shows only the enrolled room',async()=>{const f=setup();await f.settings('code');const invite=await f.invite();const {dom,w,errors}=screen(f,{hash:'#invite='+invite.code});try{await waitFor(()=>w.document.querySelector('#joinForm'));assert.equal(w.location.hash,'');assert.equal(w.document.querySelector('#roomCode').value,invite.code);w.document.querySelector('#studentCode').value='S001';w.document.querySelector('#joinForm').requestSubmit();await waitFor(()=>w.document.querySelector('#myRooms').textContent.includes('English'));assert(!w.document.querySelector('#myRooms').textContent.includes('Other school'));assert.deepEqual(errors,[]);}finally{dom.window.close();}});
test('student controlled names and status markup are escaped in the portal',async()=>{const f=setup();await f.settings();const c=await f.auth('<img src=x onerror=alert(1)>');await apply(f,c);const {dom,w,errors}=screen(f,{cookie:c});try{await waitFor(()=>w.document.querySelector('#myApplications article'));assert(!w.document.querySelector('#welcome img'));assert.deepEqual(errors,[]);}finally{dom.window.close();}});
